### ISSUE TITLE
changing image on header 

### ISSUE THREAD

**Issue by Gwatson2** [Gwatson2/TheLittleGreenLarderWebApplication#9]

**Comment by ben-freeman** [comment]
Here's the updated image.
<img width="48" alt="littlegreenlarderlogo" src="https://user-images.githubusercontent.com/55393692/68961692-d8c81180-07ca-11ea-8d81-fcbc7497e7cf.png">

**Comment by Gwatson2** [comment]
we can use this for the tab icon and the application icon
